test: 
	../ib hello.c.ib -i
	./hello
	rm hello
	../ib hello.cpp.ib -i
	./hello
	rm hello
	../ib hello.java.ib -i
	java hello
	rm hello.class
	../ib hello.go.ib -i
	./hello
	rm hello
	../ib stupid_prime.c.ib -i
	./stupid_prime
	rm stupid_prime
	../ib stupid_prime.java.ib -i
	java stupid_prime
	rm stupid_prime.class
